name: "dotnet-action-template"
description: ""
author: ""
inputs:
  repo-token:
    description: 'The GitHub token used to manage labels'
    required: false
    default: ${{ github.token }}
runs:
  using: "docker"
  image: "Dockerfile.Action"
  env:
    DOCKER_IMAGE: ${{ github.repository }}
    REPO-TOKEN: ${{ inputs.repo-token }}

branding:
  icon: 'file-text'
  color: 'gray-dark'
